# Generated by Django 4.0.3 on 2022-03-17 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_autor_book_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2030)])),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.ManyToManyField(to='book.year'),
        ),
    ]
