# Generated by Django 4.0.3 on 2022-04-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tags',
        ),
    ]
