# Generated by Django 4.0.3 on 2022-03-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_year_book_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='year',
            new_name='years',
        ),
    ]
