# Generated by Django 4.0.3 on 2022-04-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_book_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=70, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='pubhouse',
            name='name_house',
            field=models.CharField(max_length=70, unique=True, verbose_name='название издательства'),
        ),
    ]
