# Generated by Django 4.0.3 on 2022-03-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_rename_year_book_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
