# Generated by Django 4.0.3 on 2022-03-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_book_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Author',
        ),
    ]
