# Generated by Django 4.0.3 on 2022-04-07 18:48

import book.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_author_image_book_image_book_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=13, validators=[book.validators.phone_validator], verbose_name='телефон'),
        ),
    ]
