# Generated by Django 4.0.3 on 2022-03-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_rename_autor_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='autor',
            new_name='author',
        ),
    ]
