# Generated by Django 4.0.3 on 2022-05-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubhouse',
            name='email',
            field=models.EmailField(max_length=70, verbose_name='почта'),
        ),
    ]
