# Generated by Django 4.0.3 on 2022-05-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_pubhouse_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
    ]
