# Generated by Django 4.0.3 on 2022-03-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_pub_house_remove_book_years_delete_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pub_house',
            old_name='name',
            new_name='name_house',
        ),
    ]
