# Generated by Django 4.0.3 on 2022-03-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_book_place_book_book_place'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pub_house',
            new_name='PubHouse',
        ),
    ]
