# Generated by Django 4.0.3 on 2022-03-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_rename_pub_house_pubhouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.CharField(choices=[('solid', 'Твердый переплет'), ('soft', 'Мягкий переплет')], default='solid', max_length=10, verbose_name='переплет'),
        ),
    ]
