# Generated by Django 4.0.3 on 2022-03-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_users_age_users_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='users',
            field=models.ManyToManyField(to='book.users'),
        ),
    ]
