# Generated by Django 4.0.3 on 2022-03-29 11:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_remove_book_users_users_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='стелаж')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='порядковый норме')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.CharField(max_length=70, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='author',
            name='firstname',
            field=models.CharField(max_length=70, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='lastname',
            field=models.CharField(max_length=70, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='pubhouse',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='pubhouse',
            name='email',
            field=models.CharField(max_length=70, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='pubhouse',
            name='name_house',
            field=models.CharField(max_length=70, verbose_name='название издательства'),
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=70, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='users',
            name='firstname',
            field=models.CharField(max_length=70, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastname',
            field=models.CharField(max_length=70, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_place',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.bookplace'),
        ),
        migrations.DeleteModel(
            name='Book_Place',
        ),
    ]
