# Generated by Django 4.0.3 on 2022-03-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_bookplace_alter_author_email_alter_author_firstname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'автор', 'verbose_name_plural': 'авторы'},
        ),
        migrations.AlterModelOptions(
            name='bookplace',
            options={'verbose_name': 'место книги', 'verbose_name_plural': 'места книг'},
        ),
        migrations.AlterModelOptions(
            name='pubhouse',
            options={'verbose_name': 'издание', 'verbose_name_plural': 'издания'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='почта'),
        ),
    ]
